### ISSUE TITLE
Recipe Blacklist is broken in ProRecipes 2.0.2

### ISSUE THREAD

**Issue by Zomblad** [mcgrizzz/ProRecipes#12]
Hello there. For some reason "recipeBlacklist" option from config.yml breaks the whole plugin. I was trying to disable vanilla tnt recipe, but it not worked. Look at my configs:
```
checkUpdate: false
spigot: true
showPrompts: true
recipeBlacklist: 
- tnt!0
```

Also plugin shows error on server start up:
```
[10:32:02 INFO]: [ProRecipes] Enabling ProRecipes v2.0.2
[10:32:02 INFO]: [ProRecipes] Version detected for NBTTag support!: v1_12_R1
[10:32:02 INFO]: Thank you for purchasing ProRecipes! 
Any comments or concerns message me on spigot!
[10:32:02 ERROR]: Error occurred while enabling ProRecipes v2.0.2 (Is it up to date?)
java.lang.UnsupportedOperationException: null
	at com.google.common.collect.UnmodifiableIterator.remove(UnmodifiableIterator.java:46) ~[craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.RecipeIterator.remove(RecipeIterator.java:51) ~[craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
	at mc.mcgrizzz.prorecipes.ProRecipes.removeBlacklist(ProRecipes.java:352) ~[?:?]
	at mc.mcgrizzz.prorecipes.ProRecipes.onEnable(ProRecipes.java:191) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by TrademarkTM** [comment]
Having the same problem here.
Hope this can be fixed soon!

Thanks.

**Comment by mcgrizzz** [comment]
1.12 not yet supported, please check back in a day or two.
