### ISSUE TITLE
Error on starting at spigot 1.12

### ISSUE THREAD

**Issue by d3sknight** [mcgrizzz/ProRecipes#15]
Console log

```
[ProRecipes] Enabling ProRecipes v2.0.2
[05:01:56 INFO]: [ProRecipes] Version detected for NBTTag support!: v1_12_R1
[05:01:56 INFO]: [ProRecipes] Checking for updates...
[05:01:56 WARN]: [AutoSaveWorld] Plugin ProRecipes attempted to establish connection https://raw.githubusercontent.com/mcgrizzz/PluginVersions/master/versions.txt in main server thread
[05:01:57 WARN]: [AutoSaveWorld] Plugin ProRecipes attempted to establish connection socket://raw.githubusercontent.com:443 in main server thread
[05:01:57 INFO]: [ProRecipes] Up to date!
[05:01:57 INFO]: Thank you for purchasing ProRecipes!
Any comments or concerns message me on spigot!
[05:01:57 ERROR]: Error occurred while enabling ProRecipes v2.0.2 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at com.google.common.collect.UnmodifiableIterator.remove(UnmodifiableIterator.java:46) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.RecipeIterator.remove(RecipeIterator.java:51) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-596221b-9a1fc1e]
        at mc.mcgrizzz.prorecipes.ProRecipes.removeBlacklist(ProRecipes.java:350) ~[?:?]
        at mc.mcgrizzz.prorecipes.ProRecipes.onEnable(ProRecipes.java:191) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```

**Comment by mcgrizzz** [comment]
1.12 is not yet supported.
