### ISSUE TITLE
java.lang.Throwable:

### ISSUE THREAD

**Issue by SlayG** [mcgrizzz/ProRecipes#26]
The errors seem to be negligible but I still wanted to bring it to your attention, see below. Thanks!

```
18.06 18:21:24 [Server] WARN java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
18.06 18:21:24 [Server] WARN at org.bukkit.inventory.ShapelessRecipe.<init>(ShapelessRecipe.java:26)
18.06 18:21:24 [Server] WARN at me.mcgrizzz.prorecipes.recipes.RecipeShapeless.<init>(RecipeShapeless.java:30)
18.06 18:21:24 [Server] WARN at me.mcgrizzz.prorecipes.recipes.Recipes.afterCraft(Recipes.java:1735)
18.06 18:21:24 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor222.execute(Unknown Source)
18.06 18:21:24 [Server] WARN at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
18.06 18:21:24 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
18.06 18:21:24 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
18.06 18:21:24 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527)
18.06 18:21:24 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512)
18.06 18:21:24 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1981)
18.06 18:21:24 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
18.06 18:21:24 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
18.06 18:21:24 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
18.06 18:21:24 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
18.06 18:21:24 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
18.06 18:21:24 [Server] WARN at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
18.06 18:21:24 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
18.06 18:21:24 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
18.06 18:21:24 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
18.06 18:21:24 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
18.06 18:21:24 [Server] WARN at java.lang.Thread.run(Thread.java:748)
```

**Comment by mcgrizzz** [comment]
Yes, this is not an error but a "warning." Due to a recipe API overhaul in the Spigot API, ProRecipes is currently using deprecated methods to maintain backwards compatibility.

**Comment by Joapple** [comment]
Is there a way to "hide" those warnings?
