### ISSUE TITLE
ProRecipes 2.1.3 fails to open on 1.13

### ISSUE THREAD

**Issue by CaszGamerMD** [mcgrizzz/ProRecipes#34]
error:
[17:46:15 ERROR]: Error occurred while enabling ProRecipes v2.1.3 (Is it up to date?)
java.lang.IllegalArgumentException: Cannot open an inventory of type CREATIVE
	at org.apache.commons.lang.Validate.isTrue(Validate.java:71) ~[patched_1.13.jar:git-Paper-109]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.createInventory(CraftServer.java:1607) ~[patched_1.13.jar:git-Paper-109]
	at mc.mcgrizzz.prorecipes.ProRecipes.setupRecipes(ProRecipes.java:428) ~[?:?]
	at mc.mcgrizzz.prorecipes.ProRecipes.onEnable(ProRecipes.java:205) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.13.jar:git-Paper-109]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.jar:git-Paper-109]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.jar:git-Paper-109]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:432) ~[patched_1.13.jar:git-Paper-109]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:346) ~[patched_1.13.jar:git-Paper-109]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:589) ~[patched_1.13.jar:git-Paper-109]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:551) ~[patched_1.13.jar:git-Paper-109]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:428) ~[patched_1.13.jar:git-Paper-109]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:305) ~[patched_1.13.jar:git-Paper-109]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:764) ~[patched_1.13.jar:git-Paper-109]
	at java.lang.Thread.run(Thread.java:844) [?:?]

**Comment by mcgrizzz** [comment]
Fixed as of commit 2ad23765c46573fd9aee0eed55d954e6735fa49b
