### ISSUE TITLE
Unable to delete recipe

### ISSUE THREAD

**Issue by kmccmk9** [mcgrizzz/ProRecipes#9]
Currently when I click accept or decline, nothing happens. If I move the blocks within the crafting square, nothing happens. If I drop the block in my inventory nothing happens. If I drop the block directly on the ground from the crafting square nothing happens. It certainly is not instantaneous like it shows in the demo video. Not sure if I'm doing something wrong perhaps but my other admins on my server also have a problem.

**Comment by mcgrizzz** [comment]
Is there an error in the console, what version are you on? Can you provide video, GIFs or screenshots displaying the issue?

**Comment by kmccmk9** [comment]
Absolutely! Here is what is going on...

**Error in console:**

```
[00:11:00 ERROR]: Could not pass event InventoryClickEvent to ProRecipes v2.0.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-c765646]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-c765646]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-4bd94dc-c765646]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot-1.12.2.jar:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.12.2.jar:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-4bd94dc-c765646]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-c765646]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.UnsupportedOperationException
        at com.google.common.collect.UnmodifiableIterator.remove(UnmodifiableIterator.java:46) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-c765646]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.RecipeIterator.remove(RecipeIterator.java:51) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-c765646]
        at mc.mcgrizzz.prorecipes.RecipeShaped.unregister(RecipeShaped.java:1040) ~[?:?]
        at mc.mcgrizzz.prorecipes.RecipeManager.onInventoryClick(RecipeManager.java:1034) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor234.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-c765646]
        ... 15 more
```

**GIF:** 
[Gif of Problem](https://imgur.com/gd8sWKC)

**Comment by mcgrizzz** [comment]
This seems to be an issue with 1.12. I'm looking into a fix right now. I will close this when it's resolved. If you have update checking enabled you should get a notification. Thanks for letting me know.

**Comment by kmccmk9** [comment]
No problem, let me know if I can help in any way

**Comment by mcgrizzz** [comment]
Addressed in most recent commit.
